### ISSUE TITLE
Slider设置的marks单位不一样的时候，字体挤到一起

### ISSUE THREAD

**Issue by wangning110** [ksc-fe/kpc#200]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - Framework [e.g. react]

**Additional context**

- 

-

**Comment by Javey** [comment]
默认最后一个标签会右端对齐，可以适当增加`Slider`宽度，或者添加如下样式让最后一个标签也居中对齐
```css
.k-slider .k-marks > span:last-child {
    transform: translateX(-50%);
}
```
