### ISSUE TITLE
下拉框高度不可配置

### ISSUE THREAD

**Issue by jktantan** [ksc-fe/kpc#427]
发现所有有下拉框的组件的，下拉框的高度都是写死的。
能否开放这个高度配置。可选择项为：默认，px高度，100%。
再程序控制一下如果手动配置的高度超高就使用100%的高度？

**Comment by Javey** [comment]
是指的`Select`下拉框的高度，这个的确是有个最大高度，如果你想改变该高度，可以通过css控制
```css
.k-select-dropdown {
    max-height: none; /* 去掉高度限制 */
}
```
